src/FUB/GeneralBundle/Entity/Annonces.php
<?php
/**
 * Created by IntelliJ IDEA.
 * User: root
 * Date: 4/18/17
 * Time: 2:40 PM
 */

namespace FUB\GeneralBundle\Entity;

namespace FUB\GeneralBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="annonces")
 */
class Annonces
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $upd_dt;

    /**
     * @ORM\Column(type="string")
     */
    private $contenu;

    /**
     * @ORM\Column(type="string")
     */
    private $status;


    private $create;


    /**
     * @return mixed
     */
    public function getCreate()
    {
        return $this->create;
    }

    /**
     * @return mixed
     */
    public function getUpdDt()
    {
        return $this->upd_dt;
    }

    /**
     * @param mixed $upd_dt
     */
    public function setUpdDt($upd_dt)
    {
        $this->upd_dt = $upd_dt;
    }

    /**
     * @return mixed
     */
    public function getContenu()
    {
        return $this->contenu;
    }

    /**
     * @param mixed $contenu
     */
    public function setContenu($contenu)
    {
        $this->contenu = $contenu;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param mixed $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

}

src/FUB/GeneralBundle/Controller/DefaultController.php
<?php

namespace FUB\GeneralBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Ob\HighchartsBundle\Highcharts\Highchart;


class DefaultController extends Controller
{
    public function indexAction()
    {
        $listAnnonce=$this->getDoctrine()
            ->getRepository('FUBGeneralBundle:Annonces')
            ->findBy(array('status'=>'enable'),array('id'=>'DESC'),array('limit'=>'1'))
        ;
        return $this->render('FUBGeneralBundle:Default:index.html.twig',array(
            'annonces'=>$listAnnonce
        ));
    }

    public function ruleAction()
    {
        return $this->render('FUBGeneralBundle:Default:rules.html.twig');
    }

    public function adhesionAction()
    {
        return $this->render('FUBGeneralBundle:Default:adhesionForm.html.twig');
    }

    public function contactAction()
    {
        return $this->render('FUBGeneralBundle:Default:contact.html.twig');
    }
}

src/FUB/GeneralBundle/Resources/views/Default/adhesionForm.html.twig
{% extends '::base.html.twig' %}
{% block title %}Formulaire d'adhésion{% endblock %}
{% block body%}
    <div class="container" style="margin-top: 70px; width: 90%;">
        <div class="alert alert-info" role="alert">
            Formulaire d'adhésion à remplir pour investir chez <b>FREE-UNITED-BUSINESS</b>
        </div>

        <div class="alert alert-warning" role="alert"><b><u>Note:</u></b> Apres l'examen de votre dossier, nous vous enverrons par la suite
            le contrat à signer, puis de nous le remettre à nouveau.
        </div>

        {% block formulaire %}
            {{ form_start(form2, {'attr': {'class': 'form-horizontal'}}) }}
            {{ form_errors(form2) }}
            <div class="container">
                Télécharger le formulaire de demande d'adhésion
                <a class="btn btn-primary" href="{{ asset('download/article.pdf') }}">Télécharger</a></br></br>
            </div>

            <div class="container">
                Puis nous l'envoyer au format PDF une fois rempli.</br>{{ form_widget(form2.file, {'attr': {'class': 'btn btn-primary'}}) }}</br>
                {{ form_widget(form2.upload, {'attr': {'class': 'btn btn-primary'},'label':'Envoyer'}) }}</br></br>
                Ou bien de remplir le formulaire d'adhésion ci-dessous.</br></br>
            </div>
            {{ form_rest(form2) }}
            {{ form_end(form2) }}

            {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
            {{ form_errors(form) }}
            <div class="form-group">
                <table style="margin: 0 auto" width="90%" class="table table-bordered">
                    <tr>
                        <td>{{ form_label(form.picture, "Photo", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.picture) }}
                        </td>
                        <td colspan="3">
                            {{ form_widget(form.picture, {'attr': {'class': 'btn btn-primary'}}) }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form_label(form.nom, "Nom", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.nom) }}
                        </td>
                        <td>
                            {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
                        </td>
                        <td>
                            {{ form_label(form.prenom, "Prénom(s)", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.prenom) }}
                        </td>
                        <td>
                            {{ form_widget(form.prenom, {'attr': {'class': 'form-control'}}) }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form_label(form.dateNaissance, "Date de naissance (dd-MM-yyyy)", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.dateNaissance) }}
                        </td>
                        <td>
                            {{ form_widget(form.dateNaissance, {'attr': {'class': 'form-control'}}) }}
                        </td>
                        <td>
                            {{ form_label(form.profession, "Profession", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.profession) }}
                        </td>
                        <td>
                            {{ form_widget(form.profession, {'attr': {'class': 'form-control'}}) }}
                        </td>
                    </tr>
                    <tr>
                        <th rowspan="2">
                            Filiation
                        </th>
                        <td>
                            {{ form_label(form.perenom, "Père", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.perenom) }}
                        </td>
                        <td colspan="2">
                            {{ form_widget(form.perenom, {'attr': {'class': 'form-control'}}) }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form_label(form.merenom, "Mère", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.merenom) }}
                        </td>
                        <td colspan="2">
                            {{ form_widget(form.merenom, {'attr': {'class': 'form-control'}}) }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form_label(form.nationalite, "Nationalité", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.nationalite) }}
                        </td>
                        <td>
                            {{ form_widget(form.nationalite, {'attr': {'class': 'form-control'}}) }}
                        </td>
                        <td>
                            {{ form_label(form.adresse, "Adresse", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.adresse) }}
                        </td>
                        <td>
                            {{ form_widget(form.adresse, {'attr': {'class': 'form-control'}}) }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form_label(form.ville, "Ville", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.ville) }}
                        </td>
                        <td>
                            {{ form_widget(form.ville, {'attr': {'class': 'form-control'}}) }}
                        </td>
                        <td>
                            {{ form_label(form.country, "Pays", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.country) }}
                        </td>
                        <td>
                            {{ form_widget(form.country, {'attr': {'class': 'form-control'}}) }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form_label(form.contact, "Contact", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.contact) }}
                        </td>
                        <td>
                            <div class="input-group">
                                <span class="input-group-addon">+</span>{{ form_widget(form.contact, {'attr': {'class': 'form-control'}}) }}
                            </div>
                        </td>
                        <td>
                            {{ form_label(form.mail, "E-mail", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.mail) }}
                        </td>
                        <td>
                            <div class="input-group">
                                <span class="input-group-addon">@</span>{{ form_widget(form.mail, {'attr': {'class': 'form-control'}}) }}
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <th rowspan="2">Montant à investir</th>
                        <td>
                            {{ form_label(form.montantChiffre, "en chiffre", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.montantChiffre) }}
                        </td>
                        <td colspan="2">
                            <div class="input-group">
                                <span class="input-group-addon">Ar</span>{{ form_widget(form.montantChiffre, {'attr': {'class': 'form-control'}}) }}
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form_label(form.montantLettre, "en lettre", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.montantLettre) }}
                        </td>
                        <td colspan="2">
                            <div class="input-group">
                                <span class="input-group-addon">Ar</span>{{ form_widget(form.montantLettre, {'attr': {'class': 'form-control'}}) }}
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form_label(form.dateContrat, "Date début de contrat (dd-MM-yyyy)", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.dateContrat) }}
                        </td>
                        <td>
                            {{ form_widget(form.dateContrat, {'attr': {'class': 'form-control'}}) }}
                        </td>
                        <td>
                            {{ form_label(form.dureeContrat, "Durée du contrat", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.dureeContrat) }}
                        </td>
                        <td>
                            {{ form_widget(form.dureeContrat, {'attr': {'class': 'form-control'}}) }}
                        </td>
                    </tr>
                    <tr>
                        <th rowspan="4">Qui contacter en cas </br>de force majeur ou </br>de décès</th>
                        <td>
                            {{ form_label(form.heritieNomPrenom, "Nom et prénom(s)", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.heritieNomPrenom) }}
                        </td>
                        <td colspan="2">
                            {{ form_widget(form.heritieNomPrenom, {'attr': {'class': 'form-control'}}) }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form_label(form.heritierContact, "Contact", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.heritierContact) }}
                        </td>
                        <td colspan="2">
                            <div class="input-group">
                                <span class="input-group-addon">+</span>{{ form_widget(form.heritierContact, {'attr': {'class': 'form-control'}}) }}
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form_label(form.heritierMail, "E-mail", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.heritierMail) }}
                        </td>
                        <td colspan="2">
                            <div class="input-group">
                                <span class="input-group-addon">@</span>{{ form_widget(form.heritierMail, {'attr': {'class': 'form-control'}}) }}
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form_label(form.heritierAdresse, "Adresse", {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_errors(form.heritierAdresse) }}
                        </td>
                        <td colspan="2">
                            {{ form_widget(form.heritierAdresse, {'attr': {'class': 'form-control'}}) }}
                        </td>
                    </tr>
                    <tr>
                        <th rowspan="2">Sondage</th>
                        <th>
                            Comment aviez-vous</br>connu FUB?
                            {{ form_errors(form.sondageFub) }}
                        </th>
                        <td colspan="2">
                            {{ form_widget(form.sondageFub, {'attr': {'class': 'form-control'}}) }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Qu'est-ce qui vous</br>pousse à investir chez FUB?
                            {{ form_errors(form.motivationFub) }}
                        </th>
                        <td colspan="2">
                            {{ form_widget(form.motivationFub, {'attr': {'class': 'form-control'}}) }}
                        </td>
                    </tr>
                </table>
                <div style="margin: 10px 0 0 43%">{{ form_widget(form.valid, {'attr': {'class': 'btn btn-success'},'label': 'Envoyer la demande'}) }}</div>
            </div>

            {{ form_rest(form) }}
            {{ form_end(form) }}
        {% endblock %}
    </div>
{% endblock %}

src/FUB/GeneralBundle/Resources/views/Default/contact.html.twig
{% extends '::base.html.twig' %}
{% block title %}Contact{% endblock %}
{% block body%}
    <div class="container" style="margin-top: 70px; width: 90%;">
        <div class="thumbnail" style="text-align: center">
            <img src="{{ asset('pictures/fub.png') }}" alt="..." style="text-align: center" width="30%" height="30%">
            <div class="caption">
                <h3>FREE-UNITED-BUSINESS</h3>
                <p>NIF:3002606411 RCS:2017 B 00233</p>
                <p>STAT:4742311 11 2017 0 10246</p>
                <p>II 22 Box N108 Immeuble PARADISE Tsiazotafo</p>
                <p>Antananarivo-NADAGASCAR</p>
                <p><a href="mailto:fub@fubmad.com">fub@fubmad.com</a></p>
            </div>
        </div>

        <div class="panel panel-primary" style="text-align: center">
            <div class="panel-heading">Président</div>
            <div class="panel-body">
                <p>Mamadou Bailo BARRY</p>
                <p><a href="mailto:presidence.fub@fubmad.com">presidence.fub@fubmad.com</a></p>
                <p>+261 34 02 936 19</p>
            </div>
        </div>

        <div class="panel panel-primary" style="text-align: center">
            <div class="panel-heading">Secrétaire</div>
            <div class="panel-body">
                <p>Abdoulaye BARRY</p>
                <p><a href="mailto:secretaire.fub@fubmad.com">secretaire.fub@fubmad.com</a></p>
                <p>+261 34 68 881 65</p>
            </div>
        </div>

        <div class="panel panel-primary" style="text-align: center">
            <div class="panel-heading">Résponsable commercial</div>
            <div class="panel-body">
                <p>Ibrahima BAH</p>
                <p><a href="mailto:commercial.fub@fubmad.com">commercial.fub@fubmad.com</a></p>
                <p>+261 34 36 221 88</p>
            </div>
        </div>

        <div class="panel panel-primary" style="text-align: center">
            <div class="panel-heading">Résponsable de la communication</div>
            <div class="panel-body">
                <p>Ibrahima Sory SOW</p>
                <p><a href="mailto:communication.fub@fubmad.com">communication.fub@fubmad.com</a></p>
                <p>+261 33 31 790 50</p>
            </div>
        </div>

        <div class="panel panel-primary" style="text-align: center">
            <div class="panel-heading">Caissier</div>
            <div class="panel-body">
                <p>Alpha Oumar BAH</p>
                <p><a href="mailto:caissier.fub@fubmad.com">caissier.fub@fubmad.com
                    </a></p>
                <p>+261 34 15 347 34</p>
            </div>
        </div>
    </div>
{% endblock %}

src/FUB/GeneralBundle/Resources/views/Default/dashboard.html.twig
{% extends '::base.html.twig' %}
{% block title %}Tableau de bord{% endblock %}
{% block body%}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <div class="container-fluid" style="margin-top: 30px;">
        <div class="row">
        {% block navdash %}{% include '::navdash.html.twig' %}{% endblock %}
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

src/FUB/GeneralBundle/Resources/views/Default/index.html.twig
{% extends '::base.html.twig' %}
{% block title %}Accueil{% endblock %}
{% block body%}
    <div class="container" role="main" style="margin-top: 70px; width: 90%;">
        <!-- 16:9 aspect ratio -->

        <div data-example-id="responsive-embed-16by9-iframe-youtube">
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" src="//www.youtube.com/embed/j_CbtnUnM5g?rel=0" allowfullscreen="">
                </iframe>
            </div>
        </div>

        {% for annonce in annonces %}
            <div class="thumbnail" style="text-align: center">
                <p><h4>{{ annonce.contenu }}</h4></p>
                <p>Date éstimée du prochain investissement <h3><span class="label label-success">{{ annonce.updDt|date('d-m-Y') }}</span></h3></p>
                <p><a class="btn btn-lg btn-primary" href="{{ path('fub_general_adhesionFrom') }}">S'investir</a></p>
            </div>
        {% endfor %}

        <div id="migration" class="bs-callout bs-callout-warning">
            <h4>A propos</h4>
            <p>
                <b>FUB</b> comme son nom l'indique <b>Free United Business</b> qui signifie union libre pour le business est une société
                fondée le 03-07-2016 à Madagascar, plus précisement à Antananarivo, par des jeunes investisseurs guinéens ayant plusieurs
                années d'expérience dans le monde du commerce.
            </p>
        </div>

        <div id="migration" class="bs-callout bs-callout-warning">
            <h4>Objectif du FUB</h4>
            <p>La société s'étend sur plusieurs activités, tels que:
                <ul>
                    <li>Renforcer le tissu social</li>
                    <li>Développer l'activité économique</li>
                    <li>Promouvoir la culture</li>
                </ul>
                La société s'ouvre pour tout investisseur ayant un souhait d'élargir son business, que ce soit une personne physique ou morale qui alloue une part de capital
                disponible dans l'attente d'un retour sur investissement.
            </p>
            <p>Ainsi nous invitons ceux qui seront intéressés à nous rejoindre au titre d'investisseur de la société.</p>
        </div>
    </div>
{% endblock %}

src/FUB/GeneralBundle/Resources/views/Default/rules.html.twig
{% extends '::base.html.twig' %}
{% block title %}Règles et pré requis{% endblock %}
{% block body%}
    <div class="container"style="margin-top: 70px; width: 90%;">
        <h3>Pré requis et article de règlement</h3>
        <div class="panel panel-primary">
            <div class="panel-heading">Article 1</div>
            <div class="panel-body">
                Il n'est autorisé à devenir un investisseur de la société FUB que soit une personne morale ou une personne
                physique ayant plus de 18 ans sans distinction de sexe et/ou d'origine.
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">Article 2</div>
            <div class="panel-body">
                La convention entre la société FUB et l'investisseur se régime par un contrat, d'une durée de 12 mois renouvelable.
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">Article 3</div>
            <div class="panel-body">
                Le montant minimum pour investir dans la société FUB est évalué à (cinq million d'Ariary) 5.000.000 Ar.
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">Article 4</div>
            <div class="panel-body">
                La répartition du bénéfice sur le revenue se calculera par rapport au ratio investi de chaque investisseur,
                imputé du montant de réserve pour l'auto investissement d'une valeur de 50% du résultat net.
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">Article 5</div>
            <div class="panel-body">
                A la date d'échéance du contrat, le montant investi sera remboursé à l'investisseur.
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">Article 6</div>
            <div class="panel-body">
                L'investisseur a le droit de retirer le montant du bénéfice sous préavis de 20 jours, la société FUB
                versera à l'investisseur le monant convenu.
                <p><u>Notes:</u> le frais de la transaction sera prise en charge par l'investisseur.</p>
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">Article 7</div>
            <div class="panel-body">
                Dans le cas de décès de l'investisseur, la société versera la totalité du montant investi du défunt aux
                héritiers mentionnés dans le formulaire rempli lors du contrat.
            </div>
        </div>
    </div>
{% endblock %}